apiVersion: apps/v1
kind: Deployment
metadata:
  name: kache-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: kache
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"