apiVersion: v1
kind: Service
metadata:
  name: mix-design-service
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: mix-design
  ports:
  - protocol: http
    targetPort: 3000
    port: 80