apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kache-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aayush0325/homelab-k3s.git
    targetRevision: HEAD
    path: manifests/kache/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kache-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true