apiVersion: apps/v1
kind: Deployment
metadata:
  name: kache-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: kache
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"