apiVersion: v1
kind: Service
metadata:
  name: kache-service-clusterip
  labels:
    app: kache
spec:
  type: ClusterIP
  selector:
    app: kache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-headless
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379